source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '11.6.0'
  pod 'Firebase/Core', '11.6.0'
  pod 'Firebase/Firestore', '11.6.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
